Repository ferresys/ferresys, pull requests merged in 2023-10, with the labels that each got.

#56 Traducción y nuevas instrucciones de configuración para developers
  README.md
Labels: documentation, enhancement, changes

#61 docs/developers to main
  Backend-FerreSys/guide.md
  README.md
Labels: documentation, changes

#64 Develop/backend
  BackendFerreSys/config/index.js
  BackendFerreSys/package.json
  BackendFerreSys/src/controllers/ClientesCRUD.js
  BackendFerreSys/src/controllers/articulosCRUD.js
  BackendFerreSys/src/controllers/categoriasCRUD.js
  BackendFerreSys/src/controllers/crudController.js
  BackendFerreSys/src/controllers/detalleVentaCRUD.js
  BackendFerreSys/src/controllers/encabezadoVentaCRUD.js
  BackendFerreSys/src/controllers/kardexCRUD.js
  BackendFerreSys/src/controllers/marcasCRUD.js
  BackendFerreSys/src/controllers/permisosCRUD.js
  BackendFerreSys/src/controllers/proveedoresCRUD.js
  BackendFerreSys/src/controllers/reciboMercanciasCRUD.js
  BackendFerreSys/src/controllers/usuarioPermisosCRUD.js
  BackendFerreSys/src/controllers/usuariosCRUD.js
  BackendFerreSys/src/routes/indexRoutes.js
  package.json
Labels: changes
